<<<<<<< HEAD
source /home/gehlot/weenix/kernel/main/gdt.gdb
source /home/gehlot/weenix/kernel/mm/pagetable.gdb
source /home/gehlot/weenix/kernel/proc/kthread.gdb
source /home/gehlot/weenix/kernel/vm/vmmap.gdb
source /home/gehlot/weenix/kernel/mm/memcheck.py
source /home/gehlot/weenix/kernel/mm/page.py
source /home/gehlot/weenix/kernel/mm/slab.py
source /home/gehlot/weenix/kernel/proc/proc.py
source /home/gehlot/weenix/kernel/util/debug.py
source /home/gehlot/weenix/kernel/util/list.py
=======
source /home/amey/CS402/kernel2/k3/kernel/kernel/main/gdt.gdb
source /home/amey/CS402/kernel2/k3/kernel/kernel/mm/pagetable.gdb
source /home/amey/CS402/kernel2/k3/kernel/kernel/proc/kthread.gdb
source /home/amey/CS402/kernel2/k3/kernel/kernel/vm/vmmap.gdb
source /home/amey/CS402/kernel2/k3/kernel/kernel/mm/memcheck.py
source /home/amey/CS402/kernel2/k3/kernel/kernel/mm/page.py
source /home/amey/CS402/kernel2/k3/kernel/kernel/mm/slab.py
source /home/amey/CS402/kernel2/k3/kernel/kernel/proc/proc.py
source /home/amey/CS402/kernel2/k3/kernel/kernel/util/debug.py
source /home/amey/CS402/kernel2/k3/kernel/kernel/util/list.py
>>>>>>> 87bf8b4bd883525ad10c29c4187ae04e4414a75f
